package swing.prestamo;

import backend.ManejadorDB.libroManejadorDB;
import backend.ManejadorDB.prestamosManejadorDB;
import backend.libros.Libro;
import backend.prestamos.Prestamo;
import biblioteca.BackEnd.Excepciones.InputsVaciosException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import run.ValoresPredeterminados;

/**
 *
 * @author angelrg
 */
public class DevolverLibro extends javax.swing.JDialog {

    private ValoresPredeterminados valPre;
    private prestamosManejadorDB manejadorPrestamos;
    private Prestamo prestamo;
    private Libro libro;

    /**
     * Creates new form DevolverLibro
     */
    public DevolverLibro(boolean modal, prestamosManejadorDB manejadorPre) {
        this.manejadorPrestamos = manejadorPre;
        initComponents();
        this.setModal(modal);
    }

    public Prestamo getPrestamo() {
        return prestamo;
    }

    public void setPrestamo(Prestamo prestamo) {
        Prestamo prestamoAnt = this.prestamo;
        this.prestamo = prestamo;
        firePropertyChange("Prestamo", prestamoAnt, this.prestamo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        regresarButton = new javax.swing.JButton();
        realizarPagoButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        codigoL1FormattedTextField = new javax.swing.JFormattedTextField();
        carnetEstFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        fechaPrestamoFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        fechadevolucionFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        totalTextField = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Devolver Libro");

        regresarButton.setText("Regresar");
        regresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarButtonActionPerformed(evt);
            }
        });

        realizarPagoButton.setText("Realizar Pago");
        realizarPagoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarPagoButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Codigo del Libro:");

        try {
            codigoL1FormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-AAA")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        codigoL1FormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoL1FormattedTextFieldActionPerformed(evt);
            }
        });

        try {
            carnetEstFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("Carnet Estudiante:");

        try {
            fechaPrestamoFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("Fecha del prestamo:");

        try {
            fechadevolucionFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fechadevolucionFormattedTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fechadevolucionFormattedTextFieldFocusLost(evt);
            }
        });

        jLabel7.setText("Fecha del devolucion:");

        jLabel3.setText("Total a pagar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(regresarButton)
                            .addGap(95, 95, 95)
                            .addComponent(realizarPagoButton))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carnetEstFormattedTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codigoL1FormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalTextField)
                                    .addComponent(fechaPrestamoFormattedTextField)
                                    .addComponent(fechadevolucionFormattedTextField)))))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codigoL1FormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carnetEstFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaPrestamoFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechadevolucionFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regresarButton)
                    .addComponent(realizarPagoButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void realizarPagoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarPagoButtonActionPerformed
        try {
            if (manejadorPrestamos.cantidadDelDias(String.valueOf(prestamo.getFechaPrestamo()), fechadevolucionFormattedTextField.getText()) < 0) {
                JOptionPane.showMessageDialog(this, "Intervalo de tiempo invalido", "Error", JOptionPane.ERROR_MESSAGE);
                realizarPagoButton.setEnabled(false);
            } else {
                System.out.println(prestamo.getNo_ID() + ", " + prestamo.getCarnetEstudiante() + ", " + prestamo.getCodigoLibro() + ", " + String.valueOf(prestamo.getFechaPrestamo()) + ", " + fechadevolucionFormattedTextField.getText());
                manejadorPrestamos.devolverLibroDatos(prestamo.getNo_ID(), prestamo.getCarnetEstudiante(), prestamo.getCodigoLibro(), String.valueOf(prestamo.getFechaPrestamo()), fechadevolucionFormattedTextField.getText());
                limpiar();
                realizarPagoButton.setEnabled(true);
                JOptionPane.showMessageDialog(this, "El total es: Q " + manejadorPrestamos.Costo(fechaPrestamoFormattedTextField.getText(), fechadevolucionFormattedTextField.getText()), "Total", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            }
        } catch (InputsVaciosException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_realizarPagoButtonActionPerformed

    private void codigoL1FormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoL1FormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoL1FormattedTextFieldActionPerformed

    private void regresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarButtonActionPerformed
        limpiar();
        setPrestamo(null);
        this.setVisible(false);
    }//GEN-LAST:event_regresarButtonActionPerformed

    private void fechadevolucionFormattedTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fechadevolucionFormattedTextFieldFocusLost
        try {
            if (manejadorPrestamos.cantidadDelDias(String.valueOf(prestamo.getFechaPrestamo()), fechadevolucionFormattedTextField.getText()) < 0) {
                JOptionPane.showMessageDialog(this, "Intervalo de tiempo invalido", "Error", JOptionPane.ERROR_MESSAGE);
                realizarPagoButton.setEnabled(false);
            } else {
                realizarPagoButton.setEnabled(true);
            }
        } catch (InputsVaciosException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_fechadevolucionFormattedTextFieldFocusLost

    public void devolucion(Prestamo prestamoEditar) throws SQLException, InputsVaciosException {
        prestamo = prestamoEditar;
        System.out.println(prestamoEditar.getCarnetEstudiante() + ", " + prestamoEditar.getCodigoLibro() + ", " + String.valueOf(prestamoEditar.getFechaPrestamo()) + ", " + String.valueOf(manejadorPrestamos.fecha()));
        carnetEstFormattedTextField.setText(prestamoEditar.getCarnetEstudiante());
        carnetEstFormattedTextField.setEnabled(false);
        codigoL1FormattedTextField.setText(prestamoEditar.getCodigoLibro());
        codigoL1FormattedTextField.setEnabled(false);
        fechaPrestamoFormattedTextField.setText(String.valueOf(prestamoEditar.getFechaPrestamo()));
        fechaPrestamoFormattedTextField.setEnabled(false);
        fechadevolucionFormattedTextField.setText(String.valueOf(manejadorPrestamos.fecha()));
        totalTextField.setText(manejadorPrestamos.Costo(String.valueOf(prestamoEditar.getFechaPrestamo()), String.valueOf(manejadorPrestamos.fecha())));
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField carnetEstFormattedTextField;
    private javax.swing.JFormattedTextField codigoL1FormattedTextField;
    private javax.swing.JFormattedTextField fechaPrestamoFormattedTextField;
    private javax.swing.JFormattedTextField fechadevolucionFormattedTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton realizarPagoButton;
    private javax.swing.JButton regresarButton;
    private javax.swing.JTextField totalTextField;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
        carnetEstFormattedTextField.setText("");
        codigoL1FormattedTextField.setText("");
        fechaPrestamoFormattedTextField.setText("");
        fechadevolucionFormattedTextField.setText("");
    }
}
